---
- name: Load base vars
  include_vars:
    file: base.yml
    name: base_vars

- name: Load profile vars
  include_vars:
    file: "{{ metadata.profile | default('s3') }}.yml"
    name: profile_vars

- set_fact:
    loaded_artifact: '{{ base_vars | combine(profile_vars | default({}), recursive=True) }}'
