---
_definition:
  arguments:
    image:
      description: The Droplet image ID or slug.
      required: yes
    name:
      description: The Droplet name
      required: yes
    region:
      description: The region to start in
      required: yes
    size:
      description: The instance size to start
      required: yes
    backups:
      description: Boolean controlling if backups are made. Defaults to false.
    monitoring:
      description: Boolean controlling whether monitoring agent is installed. Defaults to false.
    ipv6:
      description: Boolean controlling if IPv6 is enabled. Defaults to false.
    private_networking:
      description: Boolean controlling if private networks are enabled. Defaults to false.
    ssh_keys:
      description: A list of SSH IDs or fingerprints to enable in the format [12345, 123456]. To retrieve this info, use a tool such as curl with the DigitalOcean API, to retrieve them.
    resize_disk:
      description: Boolean controlling whether to increase the disk size when resizing a Droplet. It defaults to true. When set to false, only the Droplet's RAM and CPU will be resized. Increasing a Droplet's disk size is a permanent change. Increasing only RAM and CPU is reversible.
    tags:
      description: A list of the tags to label this droplet. A tag resource must exist before it can be associated with a droplet.
    user_data:
      description: A string of the desired User Data for the Droplet.
    volume_ids:
      description: A list of the IDs of each block storage volume to be attached to the Droplet.
  attributes:
    ipv4_address:
      description: The IPv4 address
      required: yes
