---
- set_fact:
    user_artifact: {}

- name: '^^^^^ BEGIN USER PROMPT ^^^^^ {{ component_role }}'
  include_role:
    name: terraplate/spec
    tasks_from: debug
  vars:
    debug_items: [component, reference_component]

- name: Set values on component elements that are either required or variables
  include_tasks: prompt.yml
  vars:
    default: "{{ component.value[question.key] | default('') }}"
  with_dict: '{{ reference_component._definition.arguments | default({}) }}'
  loop_control:
    loop_var: question
  when: question.value.required is defined or question.value.variable is defined

- name: '^^^^^ END USER PROMPT ^^^^^ {{ component_role }}'
  include_role:
    name: terraplate/spec
    tasks_from: debug
  vars:
    debug_items: [user_artifact]
