---
- name: "Debug question '{{ question.key }}'"
  include_role:
    name: terraplate/spec
    tasks_from: debug
  vars:
    debug_items: [question, default]

- name: "Provide the value for the {{ component.key }} '{{ question.key }}'"
  prompt:
    msg:
      say: "\n{{ question.value.description }}\n{{ component.key }} '{{ question.key }}'"
      ask: answer
      default: '{{ default }}'
  when: default is string

- name: Update user_artifact with value from prompt
  set_fact:
    user_artifact: '{{ user_artifact | combine({question.key: answer}, recursive=True)}}'
  when: default is string
