---
- name: Template the application terraform.tfvars file
  template:
    src: terraform.tfvars.j2
    dest: '{{ spec.terraplate.root_dir }}/terraform.tfvars'

- name: Template the credentials.tfvars file
  import_role:
    name: terraplate/utils
    tasks_from: template-key-value-pairs
  vars:
    dest: '{{ spec.terraplate.credentials_dir }}'
    template_vars: '{{ terraplate_credentials }}'
  when: terraplate_credentials is defined
