---
- name: Template the application terraform.tfvars file
  template:
    src: terraform.tfvars.j2
    dest: '{{ spec.terraplate.root_dir }}/terraform.tfvars'

- name: Template the credentials.tfvars file
  template:
    src: credentials.tfvars.j2
    dest: '{{ manifest.spec.application.terraplate.credentials_path }}'
  when: terraplate_credentials is defined
