---
_definition:
  arguments:
    alias:
      type: map
      required: yes
      arguments:
        evaluate_target_health:
          description: description
          required: yes
        name:
          description: The name of the DNS record to alias
          required: yes
          reference_from:
            aws_elb: dns_name
            aws_s3_bucket: website_domain
            aws_cloudfront_distribution: domain_name
        zone_id:
          description: The zone id of the resource being aliased
          required: yes
          reference_from:
            aws_elb: zone_id
            aws_s3_bucket: hosted_zone_id
            aws_cloudfront_distribution: hosted_zone_id

alias:
  evaluate_target_health: 'true'
type: 'A'
