---
_definition:
  arguments:
    records:
      description: The resource records
      required: yes
      type: list
      reference_from:
        aws_eip: public_ip
    ttl:
      description: The TTL of the DNS record cache
      required: yes

ttl: '300'
