---
_definition:
  arguments:
    records:
      description: The resource records
      required: yes
      type: list
      reference_from:
        aws_eip: public_ip
    ttl:
      description: The TTL of the DNS record cache
      required: yes

type: 'NS'
ttl: '300' # '172800'
records:
  - "${aws_route53_zone.{{ component.value.subdomain.split('/') | last }}.name_servers.0}"
  - "${aws_route53_zone.{{ component.value.subdomain.split('/') | last }}.name_servers.1}"
  - "${aws_route53_zone.{{ component.value.subdomain.split('/') | last }}.name_servers.2}"
  - "${aws_route53_zone.{{ component.value.subdomain.split('/') | last }}.name_servers.3}"
