---
resource:
  meta:
    type: aws_iam_policy_document
    description: Generates an IAM policy document in JSON format.

  #
  # variables:
  #   bucket:
  #     description: 'The name of the S3 bucket to which the application will be deployed'
  #   cidr_blocks:
  #     description: 'The IP address that may access the bucket'
  #     default: 0.0.0.0/0
  # 
  # input_vars:
  #   iam_user_arn:
  #     description: description
  #     default: ''
  
  output_vars:
    json:
      description: The json representation of the policy document
      prefix: data.
