---
# - debug:
#     var: '{{ debug_item }}'
#     verbosity: 1
#   with_items: [resource_name, resource, user_resource_variables, template_name]
#   loop_control:
#     loop_var: debug_item

- name: "Render the resource template for {{ resource.meta.type + '_' + resource_name | replace('-', '_') }}"
  template:
    src: main.tf.j2 # This could be changed to resource.tf.j2
    # src: "{{ template_name | default('main.tf.j2') }}"
    dest: "{{ spec.terraplate.component_dir }}/{{ resource.meta.type + '_' + resource_name | replace('-', '_') }}.tf"
  # when: this is a resource; Next task would template when it is data
