---
_definition:
  arguments:
    token:
      description: This is the GitHub personal access token. It must be provided, but it can also be sourced from the GITHUB_TOKEN environment variable.
      required: yes
      variable: yes
  
    organization:
      description: This is the target GitHub organization to manage. The account corresponding to the token will need 'owner' privileges for this organization. It must be provided, but it can also be sourced from the GITHUB_ORGANIZATION environment variable.
      required: yes
  
    base_url: 
      description: This is the target GitHub base API endpoint. Providing a value is a requirement when working with GitHub Enterprise. It is optional to provide this value and it can also be sourced from the GITHUB_BASE_URL environment variable. The value must end with a slash.

organization: _key_
