---
m1:
  components_dir: "{{ role_path.split('/')[0:-2] | join('/') }}/providers"

m0:
  module_source_dir: "{{ role_path.split('/')[0:-2] | join('/') }}/modules"
  module_target_dir: 'terraform/modules'
  module_provider: "{{ module_name.split('-')[0:2] | join('-') }}-modules"

module_vars:
  name: '{{ module_name }}'
  provider_name: '{{ m0.module_provider }}'
  source_dir: '{{ m0.module_source_dir }}/{{ m0.module_provider }}'
  source_file: '{{ m0.module_source_dir }}/{{ m0.module_provider }}/{{ module_name }}.yml'
  target_dir: '{{ m0.module_target_dir }}/{{ m0.module_provider }}/{{ module_name }}'

p0:
  plan_source_dir: 'plans'
  plan_target_dir: 'terraform/plans'
  plan_application: "{{ plan_name.split('/')[0:1] | join('/') }}"
  plan_environment: "{{ '' if plan_environment == '' else plan_environment + '/' }}"
  plan_namespace: "{{ plan_name.split('/')[1:] | join('/') }}"

plan_vars:
  name: '{{ plan_name }}'
  source_dir: '{{ p0.plan_source_dir }}/{{ plan_name }}'
  target_dir: '{{ p0.plan_target_dir }}/{{ p0.plan_application }}/{{ p0.plan_environment }}{{ p0.plan_namespace }}'
