---
- name: Check if artifact vars_file exists
  stat:
    path: '{{ reference_artifact_vars_file_path }}'
  register: vars_file

- name: Include reference_artifact vars file from file
  include_vars:
    file: '{{ reference_artifact_vars_file_path }}'
    name: vars_loaded_artifact
  when: vars_file.stat.exists

- set_fact:
    loaded_artifact: '{{ vars_loaded_artifact }}'
  when: vars_file.stat.exists

- name: Include reference_artifact vars file from role
  include_role:
    name: '{{ reference_artifact_path }}'
  when: not vars_file.stat.exists

- debug:
    var: '{{ debug_item }}'
    verbosity: 0
  with_items: [reference_artifact, user_artifact, artifact, artifact_definition]
  loop_control:
    loop_var: debug_item

- name: "Render the artifact template for {{ artifact_full_name }}"
  template:
    src: main.tf.j2
    dest: "{{ spec.terraplate.component_dir }}/{{ artifact_full_name }}.tf"
  when: spec.terraplate.monolithic_file_name is not defined

- name: "Render the artifact template for {{ artifact_full_name }}"
  blockinfile:
    create: yes
    dest: "{{ spec.terraplate.component_dir }}/{{ spec.terraplate.monolithic_file_name }}.tf"
    marker: '# {mark} {{ artifact_full_name }}'
    block: "{{ lookup('template', 'main.tf.j2') }}"
  when: spec.terraplate.monolithic_file_name is defined
