# See: https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Scenario1.html
---
env_spec:
  - metadata:
      type: aws
    resources:
      - metadata:
          type: aws_vpc
          name: dink
        arguments:
          cidr_block: 172.16.0.0/20
          tags:
            Name: This great VPC1
            Environment: '{{ env.terraplate.tld }}'
        resources:
          - metadata:
              type: aws_subnet
              name: dink_public_1
              prefix_name_with_parent: yes
            arguments:
              availability_zone: ap-southeast-1a
              map_public_ip_on_launch: yes
              cidr_block: 172.16.0.0/24
              tags:
                Name: 'public-1'
            # - name: public_2
            #   availability_zone: ap-southeast-1b
            #   cidr_block: 172.16.2.0/24
            #   tags: { Name: 'public-2' }
            #   rtb: route-table
            # - name: private_1
            #   availability_zone: ap-southeast-1a
            #   cidr_block: 172.16.1.0/24
            #   tags: { Name: 'private-1' }
            #   rtb: vpc
            #   map_public_ip_on_launch: 'false'
            # - name: private_2
            #   availability_zone: ap-southeast-1b
            #   cidr_block: 172.16.3.0/24
            #   tags: { Name: 'private-2' }
            #   rtb: vpc
            #   map_public_ip_on_launch: 'false'

      - metadata:
          type: aws_internet_gateway
          name: main
        arguments:
          vpc_id: aws_vpc.dink
      - metadata:
          type: aws_route_table
          name: route_to_igw
        arguments:
          vpc_id: aws_vpc.dink
          tags:
            Name: route-to-igw
        resources:
          - metadata:
              type: aws_route
              name: default_route
            arguments:
              gateway_id: aws_internet_gateway.main
          - metadata:
              type: aws_route_table_association
              name: route_to_igw_to_dink_public_1
            arguments:
              subnet_id: aws_subnet.dink_public_1
