---
env_spec:
  - metadata:
      type: aws
    #
    # data_sources:
    #   - metadata:
    #       type: terraform_remote_state
    #       name: network
    resources:
      - metadata:
          type: aws_security_group
          name: app_server
        arguments:
          description: app-server-security-group
          tags:
            Name: app-server
          vpc_id: network:aws_vpc:dink
          # vpc_id: aws_vpc:dink
          # vpc_id: ${data.terraform_remote_state.network.aws_vpc_dink_id}
        resources:
          - metadata:
              type: aws_security_group_rule
              name: allow_ssh_in
            arguments:
              to_port: 22
              type: ingress
              cidr_blocks: ['0.0.0.0/0']
          - metadata:
              type: aws_security_group_rule
              name: allow_all_out
            arguments:
              protocol: -1
              type: egress
              cidr_blocks: ['0.0.0.0/0']
      #
      # - name: alb
      #   description: alb-security-group
      #   tags:
      #     Name: alb
      #   vpc_id: ${data.terraform_remote_state.network.aws_vpc_dink_id}
      #   rules:
      #     - name: allow_http_in
      #       to_port: 80
      #       type: ingress
      #       cidr_blocks: ['0.0.0.0/0']
      #     - name: allow_https_in
      #       to_port: 443
      #       type: ingress
      #       cidr_blocks: ['0.0.0.0/0']
      #     - name: allow_https2_in
      #       to_port: 1443
      #       type: ingress
      #       cidr_blocks: ['0.0.0.0/0']
