---
env_spec:
  resources:
    aws_instances:
      - _id: rails_server_1
        amis: '{{ global_vars.amis.debian_stretch }}'
        region: ap-southeast-1
        subnet_id: ${data.terraform_remote_state.app-network.aws_subnet_public_1_subnet_id}
        vpc_security_group_ids: ['${data.terraform_remote_state.app-security.aws_security_group_app-server_security_group_id}']
        availability_zone: ap-southeast-1a
        # Note: Tags can be associated to ansible roles for configuration after provisioning
        tags:
          Name: This great Instance
          Environment: '{{ env.terraplate.tld }}'
          Role-rails-server: 'yes'
        key_name: '{{ settings.ec2_key_name }}'
        root_block_device:
          volume_size: '12'
    aws_eips:
      - _id: rails_server_1_eip
        instance: ${aws_instance.rails_server_1.id}
    records:
      - name: 'server1-{{ env.terraplate.tld }}.{{ settings.zone_domain }}'
        zone_id: "${data.terraform_remote_state.dns.domain.aws_route53_zone_{{ settings.zone_domain | replace('.', '-') }}_zone_id}"
        type: 'A'
        records: ['${aws_eip.rails_server_1_eip.public_ip}']
