---
- name: Load records vars
  include_vars:
    file: records.yml
    name: role_loaded_artifact
  when: user_artifact.arguments.records is defined

- name: Load alias vars
  include_vars:
    file: alias.yml
    name: role_loaded_artifact
  when: user_artifact.arguments.alias is defined or user_artifact.arguments.records is not defined

- set_fact:
    loaded_artifact: '{{ role_loaded_artifact }}'
