---
metadata:
  type: aws_route53_record
  description: Provides a Route53 record aliased to a resource.
  url: https://www.terraform.io/docs/providers/aws/r/route53_record.html#alias-record

parents:
  aws_elb:
    arguments:
      alias:
        name: ${aws_elb._name_.dns_name}
        zone_id: ${aws_elb._name_.zone_id}
  aws_s3_bucket:
    arguments:
      alias:
        name: ${aws_s3_bucket._name_.website_domain}
        zone_id: ${aws_s3_bucket._name_.hosted_zone_id}

defaults:
  arguments:
    alias:
      evaluate_target_health: 'true'
    type: 'A' 

definition:
  arguments:
    alias:
      type: map
      required: yes
      arguments:
        name:
          description: The name of the DNS record to alias
          required: yes
          reference_from:
            aws_elb: dns_name
            aws_s3_bucket: website_domain
        zone_id:
          description: The zone id of the resource being aliased
          required: yes
          reference_from:
            aws_elb: zone_id
            aws_s3_bucket: hosted_zone_id
    name:
      description: The FQDN of the host
      required: yes
    type:
      description: 'The type of DNS record: A, CNAME, etc'
      required: yes
    zone_id:
      description: The zone_id of the domain in which this hostname is created
      required: yes
