---
- name: Create the application directory tree
  file:
    name: '{{ spec.terraplate.application.root_dir }}'
    state: directory

- name: Template the application terraform.tfvars file
  template:
    src: tfvars.j2
    dest: '{{ spec.terraplate.application.root_dir }}/terraform.tfvars'

- name: Template .gitignore to the application directory
  template:
    src: gitignore.j2
    dest: '{{ spec.terraplate.application.root_dir }}/.gitignore'
