# Organize manifest values in one place rather than scattered throughout the downstream templates
# in a way that makes it sensible, i.e. readable, for the templates
# This also serves to segment the user manifest from the spec used internally by components and resources
---
spec_a:
  root_dir: '{{ manifest.application.terraplate.root_dir }}'
  app_name: '{{ manifest.application.terraplate.app_name }}'
  component_name: '{{ manifest.component.terraplate.name }}'

spec_b:
  terraplate:
    root_dir: '{{ spec_a.root_dir }}'
    app_dir: '{{ spec_a.root_dir }}/{{ spec_a.app_name }}'
    credentials_dir: '{{ manifest.application.terraplate.credentials_dir }}'
    component_dir: '{{ spec_a.root_dir }}/{{ spec_a.app_name }}/{{ spec_a.component_name }}'
    component_vars_dir: '{{ manifest.application.terraplate.external_vars_dir }}/{{ spec_a.app_name }}/{{ spec_a.component_name }}'
    component_exports_dir: '{{ manifest.application.terraplate.exports_dir }}/{{ spec_a.app_name }}/{{ spec_a.component_name }}'
    component_name: '{{ spec_a.component_name }}'
    monolithic_file_name: "{{ manifest.application.terraplate.monolithic_file_name | default('component') }}"
    debug_macros: []
  terragrunt:
    credentials_path: '{{ manifest.application.terragrunt.credentials_path }}'
    component_vars_path: '{{ manifest.application.terragrunt.external_vars_path }}/{{ spec_a.app_name }}/{{ spec_a.component_name }}/vars.tfvars'
    remote_state: '{{ manifest.application.terragrunt.remote_state }}'
  terraform:

  providers:
    required: '{{ manifest.component.terraform.providers | default({}) }}'
    available: '{{ manifest.application.terraform.providers | default({}) }}'

  remote_states:
    required: '{{ manifest.component.terraform.remote_states | default([]) }}'
    available: '{{ manifest.application.terraform.remote_states | default({}) }}'
    default:
      bucket: '{{ manifest.application.terragrunt.remote_state.bucket }}'
      region: '{{ manifest.application.terragrunt.remote_state.region }}'
      key: '{{ spec_a.app_name }}'

  dependencies: '{{ manifest.component.terragrunt.dependencies | default([]) }}'
  external_vars: '{{ manifest.component.terragrunt.external_vars | default([]) }}'
