---
_definition:
  arguments:
    key_name:
      description: The name for the key pair
      required: no
    public_key:
      description: The public key material
      required: yes

  variables:
    key_path:
      description: The path to the public key contents
      required: yes

key_name: "{{ component.value.key_name | default(component.key.split('/')[2]) }}" #_key_
public_key: '${file("${var.aws_key_pair_{{ component.key.split("/")[2] }}_key_path}/{{ component.value.key_name | default(component.key.split("/")[2]) }}.pub")}'
