---
_definition:
  arguments:
    backend:
      description: The remote backend to use.
      required: yes
    config:
      description: The configuration of the remote backend.
      required: no
      type: map
    environment:
      description: The Terraform environment to use.
      required: no
    defaults:
      description: The Terraform environment to use.
      required: no
