---
- include_tasks: setup.yml
  when: false

- name: Ensure a valid project name
  fail:
    msg: Project name must be set
  when: project_name | length == 0

- name: Check if a project alredy exists
  stat:
    path: '{{ project_dir }}'
  register: project_status

- name: Quit if a project already exists
  fail:
    msg: Project already exists
  when: project_status.stat.exists

- name: Create project directory structure
  file:
    path: '{{ project_dir }}/{{ project_inventory_dir }}/group_vars/all'
    state: directory

- name: Copy the project base files
  copy:
    src: '{{ role_path }}/files/'
    dest: '{{ project_dir }}'

- name: Copy the prompt action plugin
  copy:
    src: files/action_plugins/
    dest: '{{ project_dir }}/action_plugins'

- name: Softlink to the roles directory
  file:
    src: ../../roles
    path: '{{ project_dir }}/roles'
    state: link

- name: Template the project_manifest vars
  template:
    src: terraplate.yml.j2
    dest: '{{ project_dir }}/{{ project_inventory_dir }}/group_vars/all/project_manifest.yml'

- name: Set the project's terraplate playbook to executable
  file:
    path: '{{ project_dir }}/terraplate'
    mode: 0755

- name: Generate an inventory file for localhost
  copy:
    content: "localhost ansible_connection=local\n"
    dest: '{{ project_dir }}/{{ project_inventory_dir }}/inventory'

- name: Generate the project's vault password
  copy:
    content: "{{ 999999999999999999999 | random | string + (lookup('pipe', 'date +%s%N')) | to_uuid }}"
    dest: '{{ project_dir }}/.vault-password.txt'

- name: Generate base contents for the secrets file
  copy:
    content: "---\n# provider_aws_secret_access_key: ABC123"
    dest: '{{ project_dir }}/{{ project_inventory_dir }}/group_vars/all/variables.yml'

- name: Encrypt the secrets file using the project's vault password
  command: 'ansible-vault encrypt {{ project_inventory_dir }}/group_vars/all/variables.yml'
  args:
    chdir: '{{ project_dir }}'

- name: Initialize the project's git repository
  command: '{{ item }}'
  args:
    chdir: '{{ project_dir }}'
  with_items:
    - git init
    - git add .
    - git commit -m 'first commit'
