---
- name: Check if the project alredy exists
  stat:
    path: '{{ project_dir }}'
  register: project_status

- name: Quit if the project already exists
  fail:
    msg: 'The {{ project_dir }} already exists'
  when: project_status.stat.exists

- prompt:
    msg:
      say: 'Remote State Bucket Name'
      ask: remote_state_bucket_name
      default: 'com-{{ project_name }}-terraform-state'

- prompt:
    msg:
      say: 'Remote State Bucket Region'
      ask: remote_state_bucket_region
      default: "{{ remote_state_bucket_region | default('us-east-1') }}"

- prompt:
    msg:
      say: 'Remote State Dynamodb Table'
      ask: remote_state_dynamodb_table
      default: 'com-{{ project_name }}-terraform-state'

- name: Create project directory structure
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - '{{ project_dir }}/host_vars'
    - '{{ project_dir }}/action_plugins'
    - '{{ project_dir }}/terraform/plans'

- name: Copy the project base files
  copy:
    src: '{{ role_path }}/files/'
    dest: '{{ project_dir }}'

- name: Template the project terraform.tfvars file
  template:
    src: terraform/tfvars.j2
    dest: '{{ project_dir }}/terraform/plans/terraform.tfvars'

- name: Template .gitignore to the project's terraform directory
  template:
    src: terraform/gitignore.j2
    dest: '{{ project_dir }}/terraform/.gitignore'

- name: Copy shared files to the project
  copy:
    src: "{{ role_path.split('/')[0:-3] | join('/') }}/{{ item }}"
    dest: '{{ project_dir }}/{{ item }}'
  with_items:
    - terraplate.yml
    - action_plugins/prompt.py

- name: Set the project's terraplate playbook to executable
  file:
    path: '{{ project_dir }}/terraplate.yml'
    mode: 0755

- name: Template host_vars/terraplate.yml
  template:
    src: terraplate.yml.j2
    dest: '{{ project_dir }}/host_vars/terraplate.yml'

- name: Template README.md
  template:
    src: README.md
    dest: '{{ project_dir }}/README.md'

- name: Generate the project's vault password
  copy:
    content: "{{ 999999999999999999999 | random | string + (lookup('pipe', 'date +%s%N')) | to_uuid }}"
    dest: '{{ project_dir }}/.vault-password.txt'

- name: Softlink to the roles directory
  file:
    src: ../../roles
    path: '{{ project_dir }}/roles'
    state: link

- name: Initialize the project's git repository
  command: '{{ item }}'
  args:
    chdir: '{{ project_dir }}'
  with_items:
    - git init
    - git add .
    - git commit -m 'first commit'
