---
_definition:
  arguments:
    type:
      description: Ingress or Egress rule
      required: yes
    from_port:
      description: description
      required: yes
    to_port:
      description: description
      required: yes
    protocol:
      description: description
      required: yes
    cidr_blocks:
      description: The CIDR block
      type: list
    source_security_group_id:
      description: The Security Group
    security_group_id:
      description: The id of the security group
      required: yes
      reference_from:
        aws_security_group: id

  attributes:
    id:
      description: The id of the created rule
      required: yes

type: ingress
from_port: '0'
to_port: '0'
protocol: tcp
