---
_definition:
  arguments:
    description:
      description: "The security group description. Defaults to 'Managed by Terraform'"
    name:
      description: The name of the security group. If omitted, Terraform will assign a random, unique name
    tags:
      description: A mapping of tags to assign to the resource
      type: map
      arguments: {}
    vpc_id:
      description: The id of the vpc
      reference_from:
        aws_vpc: id

  attributes:
    id:
      description: The id of the created resoruce
      required: yes
