---
metadata:
  type: aws_db_subnet_group
  description: Provides an RDS DB subnet group resource.

parents: {}

defaults: {}

definition:
  arguments:
    description:
      description: 'The description of the DB subnet group. Defaults to "Managed by Terraform".'
      required: no
    name:
      description: The name of the DB subnet group. If omitted, Terraform will assign a random, unique name.
      required: no
    name_prefix:
      description: (Forces new resource) Creates a unique name beginning with the specified prefix. Conflicts with name.
      required: no
    subnet_ids:
      description: A list of VPC subnet IDs.
      required: yes
      type: list
    tags:
      description: A mapping of tags to assign to the resource.
      required: no
      type: map
  
  attributes:
    id:
      description: The db subnet group name.
    arn:
      description: The db subnet group name.
