---
_definition:
  arguments:
    vpc:
      description: Boolean if the EIP is in a VPC or not
      required: no
    instance:
      description: EC2 instance ID
      required: no
      reference_from:
        aws_instance: id
    network_interface:
      description: Network interface ID to associate with
      required: no
    associate_with_private_ip:
      description: A user specified primary or secondary private IP address to associate with the Elastic IP address. If no private IP address is specified, the Elastic IP address is associated with the primary private IP address
      required: no
    tags:
      description: Hash of name-value pairs to tag the instance
      required: no
      type: map
  
  attributes:
    public_ip:
      description: Contains the public IP address
    id:
      description: Contains the EIP allocation ID
