---
metadata:
  type: aws_subnet
  description: Create a subnet

parents:
  aws_vpc:
    # prefix: yes
    arguments:
      vpc_id: ${aws_vpc._name_.id}

defaults:
  arguments:
    availability_zone: us-east-1a
    cidr_block: 172.16.1.0/24

definition:
  arguments:
    assign_ipv6_address_on_creation:
      description: 'Specify true to indicate that network interfaces created in the specified subnet should be assigned an IPv6 address. Default is false'
      required: no
    availability_zone:
      description: The availability zone for the subnet
      required: no
    cidr_block:
      description: The CIDR block for the Subnet
      required: yes
    ipv6_cidr_block:
      description: 'The IPv6 network range for the subnet, in CIDR notation. The subnet size must use a /64 prefix length.'
      required: no
    map_public_ip_on_launch:
      description: 'Specify true to indicate that instances launched into the subnet should be assigned a public IP address. Default is false'
      required: no
    tags:
      description: Hash of name-value pairs to tag the instance
      required: no
      type: map
    vpc_id:
      description: The id of the VPC
      required: yes
      reference_from:
        aws_vpc: id

  attributes:
    id:
      description: The id of the subnet
