---
metadata:
  type: aws_elb_attachment
  description: Provides an Elastic Load Balancer Attachment resource.

definition:
  arguments:
    elb:
      description: The name of the ELB.
      reference_from:
        aws_elb: id
      required: yes
    instance:
      description: Instance ID to place in the ELB pool.
      reference_from:
        aws_instance: id
      required: yes
