# NOTE: The certificate_chain must NOT have lines between the certificates
# Some properties of an IAM Server Certificates cannot be updated while they are in use.
# In order for Terraform to effectively manage a Certificate in this situation,
# it is recommended you utilize the name_prefix attribute and enable the create_before_destroy lifecycle block.
# This will allow Terraform to create a new, updated aws_iam_server_certificate resource and replace it
# in dependant resources before attempting to destroy the old version.

#   lifecycle {
#     create_before_destroy = true
#   }
# - name: Write to .envrc
#   blockinfile:
#     create: yes
#     dest: '{{ envrc_file }}'
#     marker: '# {mark} {{ role_path }}'
#     block: |
#       export TF_VAR_iam_server_certificate_path={{ provision.tfvars.path }}
---
metadata:
  type: aws_iam_server_certificate
  description: Create an IAM Server Certificate

parents: {}

defaults:
  arguments:
    certificate_body: ${file("${var.path}/${var.certificate_body}")}
    private_key: ${file("${var.path}/${var.private_key}")}
    certificate_chain: ${file("${var.path}/${var.certificate_chain}")}

definition:
  arguments:
    certificate_body:
      description: "The contents of the public key certificate in PEM-encoded format"
      required: yes
    certificate_chain:
      description: "The contents of the certificate chain. This is typically a concatenation of the PEM-encoded public key certificates of the chain."
      required: no
    name:
      description: "The name of the Server Certificate. Do not include the path in this value. If omitted, Terraform will assign a random, unique name."
      required: no
    private_key:
      description: "The contents of the private key in PEM-encoded format"
      required: yes

  # Needs to be set using:
  #   export TF_VAR_iam_server_certificate_path=
  variables:
    path:
      description: The path on local FS to the certificate

  attributes:
    arn:
      description: The Amazon Resource Name (ARN) specifying the server certificate
    id:
      description: The unique Server Certificate name
    name:
      description: The unique Server Certificate name
