---
metadata:
  type: aws_route
  description: Provides a resource to create a routing table entry (a route) in a VPC routing table.

parents:
  aws_route_table:
    arguments:
      route_table_id: ${aws_route_table._name_.id}

defaults:
  arguments:
    destination_cidr_block: 0.0.0.0/0

# NOTE: Each route must contain either a gateway_id, egress_only_gateway_id a nat_gateway_id, an instance_id or a
# vpc_peering_connection_id or a network_interface_id. Note that the default route, mapping the VPC's CIDR block to "local", is created implicitly and cannot be specified.
definition:
  arguments:
    destination_cidr_block:
      description: description
      required: no
    destination_ipv6_cidr_block:
      description: The destination IPv6 CIDR block.
      required: no
    vpc_peering_connection_id:
      description: An ID of a VPC peering connection.
      required: no
    egress_only_gateway_id:
      description: An ID of a VPC Egress Only Internet Gateway.
      required: no
    gateway_id:
      description: An ID of a VPC internet gateway or a virtual private gateway.
      required: no
      reference_from:
        aws_internet_gateway: id
    nat_gateway_id:
      description: An ID of a VPC NAT gateway.
      required: no
      reference_from:
        aws_nat_gateway: id
    instance_id:
      description: An ID of an EC2 instance.
      required: no
      reference_from:
        aws_instance: id
    network_interface_id:
      description: An ID of a network interface.
      required: no
    route_table_id:
      description: description
      required: yes
      reference_from:
        aws_route_table: id
  attributes:
    route_table_id:
      description: The ID of the routing table.
