---
metadata:
  type: aws_iam_access_key
  description: Provides an IAM access key. This is a set of credentials that allow API requests to be made as an IAM user

parents:
  aws_iam_user:
    arguments:
      user: ${aws_iam_user._name_.name}

defaults: {}

definition:
  arguments:
    user:
      description: The IAM user to associate with this access key
      required: yes
      reference_from:
        aws_iam_user: name
    pgp_key:
      description: Either a base-64 encoded PGP public key, or a keybase username in the form keybase:some_person_that_exists
      required: no

  attributes:
    id:
      description: The access key id
      required: yes
    user:
      description: The IAM user associated with this access key.
      required: yes
    secret:
      description: The secret access key. Note that this will be written to the state file. Please supply a pgp_key instead, which will prevent the secret from being stored in plain text
      required: yes
    ses_smtp_password:
      description: The secret access key converted into an SES SMTP password by applying AWS's documented conversion algorithm.
      required: no
