---
- include_vars:
    file: base.yml
    name: base_vars

- include_vars:
    file: '{{ metadata.profile }}.yml'
    name: profile_vars

- set_fact:
    loaded_artifact: '{{ base_vars | combine(profile_vars, recursive=True) }}'

- template:
    src: "{{ metadata.profile }}.json.j2"
    dest: '{{ spec.terraplate[build_type].target_dir }}/{{ metadata.profile.split("/") | last }}.json' 
