---
- include_vars:
    file: main_artifact.yml
    name: main_artifact

- include_vars:
    file: '{{ profile }}.yml'
    name: profile_artifact

- set_fact:
    loaded_artifact: '{{ main_artifact | combine(profile_artifact, recursive=True) }}'
