---
- include_vars:
    file: main_artifact.yml
    name: base_vars

- include_vars:
    file: '{{ metadata.profile }}.yml'
    name: profile_vars

- set_fact:
    loaded_artifact: '{{ base_vars | combine(profile_vars, recursive=True) }}'
