---
- name: Create the appliction and component vars directories
  file:
    name: '{{ item }}'
    state: directory
  with_items:
    - '{{ spec.application.inventory.dir }}'
    # - '{{ spec.application.playbook.dir }}'
    - '{{ spec.component.inventory.dir }}'

- name: Template the application arguments file
  template:
    src: manifest.yml.j2
    dest: '{{ spec.application.playbook.manifest_file }}'

- name: Get a list of the existing components for this application
  find:
    paths: '{{ spec.inventory_dir }}/host_vars'
    recurse: no
    file_type: directory
    patterns: "{{ spec.application.name }}-*"
  register: component_find

- name: Template the application inventory file
  blockinfile:
    create: yes
    dest: '{{ spec.application.inventory.file }}'
    marker: "# {mark} application '{{ spec.application.inventory.name }}'"
    block: "{{ lookup('template', 'inventory.j2') }}"
