# Component Tasks for instances-with-eip
---
- debug:
    var: spec.resources

- name: Create an EC2 instance in a VPC
  include_role:
    name: aws/ec2/instance
  vars:
    user_key: '{{ item._id }}'
    user_resource: '{{ item }}'
  with_items: '{{ spec.resources.instances }}'

- name: Create Elastic IPs
  include_role:
    name: aws/ec2/eip
  vars:
    user_key: '{{ item._id }}'
    user_resource: '{{ item }}'
  with_items: '{{ spec.resources.instances }}'
  when: item.eip is defined

#
# - name: Template the Resource Records
#   include_role:
#     name: aws/route53/record
#   vars:
#     user_key: '{{ item.name }}'
#     user_resource: '{{ item }}'
#     # user_key: "{{ (item.0.name + '-' + item.1.name + '-' + item.1.type) | replace('.', '-') }}"
#     # user_resource: "{{ item.1 | combine({'zone_id': '${aws_route53_zone.' + item.0.name | replace('.', '-') + '.id}'}) }}"
#   with_items: '{{ spec.resources.records }}'
#   # with_subelements:
#   #   - '{{ spec.resources.aws_instances }}'
#   #   - records
#   # when: item.0.records is defined
