---
- debug:
    var: manifest.spec.resources

- name: Create an EC2 instance in a VPC
  include_role:
    name: aws/ec2/instance
  vars:
    user_key: '{{ item._id }}'
    user_resource: '{{ item }}'
  with_items: '{{ manifest.spec.resources.aws_instances }}'

- name: Create Elastic IPs
  include_role:
    name: aws/ec2/eip
  vars:
    # user_key: "{{ (item.0._id + '-' + item.1._id) | replace('.', '-') }}"
    user_key: "{{ (item._id) | replace('.', '-') }}_eip"
    user_resource: '{{ item }}'
  with_items: '{{ manifest.spec.resources.aws_eips }}'

#
# - name: Template the Resource Records
#   include_role:
#     name: aws/route53/record
#   vars:
#     user_key: '{{ item.name }}'
#     user_resource: '{{ item }}'
#     # user_key: "{{ (item.0.name + '-' + item.1.name + '-' + item.1.type) | replace('.', '-') }}"
#     # user_resource: "{{ item.1 | combine({'zone_id': '${aws_route53_zone.' + item.0.name | replace('.', '-') + '.id}'}) }}"
#   with_items: '{{ manifest.spec.resources.records }}'
#   # with_subelements:
#   #   - '{{ manifest.spec.resources.aws_instances }}'
#   #   - records
#   # when: false
