---
# _metadata:
#   type: aws_s3_bucket
#   description: Creates an S3 Bucket for a website
  
_definition:
  arguments:
    acl:
      description: "The canned ACL to apply. Defaults to 'private'."
      required: no
    bucket:
      description: (Forces new resource) The name of the bucket. If omitted, Terraform will assign a random, unique name.
      required: no
    force_destroy:
      description: (Default:false) A boolean that indicates all objects should be deleted from the bucket so that the bucket can be destroyed without error. These objects are not recoverable.
      required: no
    region:
      description: If specified, the AWS region this bucket should reside in. Otherwise, the region used by the callee.
      required: no
    policy:
      description: 'A valid bucket policy JSON document. Note that if the policy document is not specific enough (but still valid), Terraform may view the policy as constantly changing in a terraform plan. In this case, please make sure you use the verbose/specific version of the policy.'
      required: no
      reference_from:
        aws_iam_policy_document: json
        aws_iam_policy: policy
        aws_s3_bucket_policy: policy

  attributes:
    arn:
      description: The ARN of the bucket. Will be of format arn:aws:s3:::bucketname.
      # required: yes
    hosted_zone_id:
      description: The Route 53 Hosted Zone ID for this bucket's region.
      # required: yes
    id:
      description: The name of the bucket.
      # required: yes
    region:
      description: The AWS region this bucket resides in.
      # required: yes
