---
defaults:
  arguments:
    acl: public-read
    force_destroy: yes
    website:
      index_document: index.html
      error_document: index.html

definition:
  arguments:
    website:
      type: map
      required: yes

  attributes:
    website_domain:
      description: The domain of the website endpoint, if the bucket is configured with a website. If not, this will be an empty string. This is used to create Route 53 alias records.
    website_endpoint:
      description: The website endpoint, if the bucket is configured with a website. If not, this will be an empty string.
