---
- name: Simple Question
  prompt:
    msg:
      say: "What is your first name?"
      ask: first_name
  when: false

- debug:
    var: first_name
  when: false

- debug:
    var: spec
  when: false
- debug:
   var: global_manifest
  when: false
# - name: Fail unless the component name is properly formatted
#   fail:
#     msg: "'component' must be in format application_name/component_name"
#   when: spec.application.name | length == 0
# - include_tasks: 'application.yml'

- include_vars:
    file: '{{ spec.template.file }}'
    name: component_manifest

- name: include tasks
  include_tasks: component.yml
  vars:
    artifact_path: resources
  with_items: '{{ component_manifest.resources }}'
  loop_control:
    loop_var: resource

- debug:
   var: component_manifest
- debug:
    var: action

    # - template:
    #     src: host_vars.yml.j2
    #     dest: '{{ spec.component.vars_file }}'

- fail:

- set_fact:
# global_manifest: {}
    application_manifest: {}
  when: template_type == 'ansible'

#
# 
- debug:
    var: spec


# BEGIN: {{ reference_artifact_path }} - Check if artifact vars_file exists'
- name: Debug the componet specification
  debug:
    var: spec 
    verbosity: 0
  when: false

- name: Template the application files
  include_role:
    name: terraplate/application
    tasks_from: '{{ template_type }}'

- name: Template the component files
  include_role:
    name: terraplate/component
    tasks_from: '{{ template_type }}'
