---
# - debug:
#    var: global_manifest
#   when: false

- include_vars:
    file: '{{ spec.template.file }}'
    name: component_spec

- debug:
   var: component_spec

# - template:
#     src: host_vars.yml.j2
#     dest: '{{ spec.component.vars_file }}'

- name: Include artifact tasks for providers
  include_role:
    name: terraplate/ansible/artifact
  vars:
    artifact_path: ''
    artifact_type: provider
  with_items: '{{ component_spec.providers }}'
  loop_control:
    loop_var: artifact
  when: component_spec.providers is defined

- name: Include artifact tasks for data_sources
  include_role:
    name: terraplate/ansible/artifact
  vars:
    artifact_path: data_sources
    # provider_type: "{{ artifact.metadata.type.split('_')[0] }}"
    artifact_type: "{{ artifact.metadata.type }}"
  with_items: '{{ component_spec.data_sources }}'
  loop_control:
    loop_var: artifact
  when: component_spec.data_sources is defined

- name: Include artifact tasks for resources
  include_role:
    name: terraplate/ansible/artifact
  vars:
    artifact_path: resources
    artifact_type: "{{ artifact.metadata.type }}"
  with_items: '{{ component_spec.resources }}'
  loop_control:
    loop_var: artifact
  when: component_spec.resources is defined
