---
# - debug: var=component

- name: Load base vars
  include_vars:
    file: base.yml
    name: base_vars

- name: Load profile vars if defined
  include_vars:
    file: '{{ metadata.profile }}.yml'
    name: profile_vars
  when: metadata.profile is defined

- set_fact:
    loaded_artifact: '{{ base_vars | combine(profile_vars | default({}), recursive=True) }}'

# - debug: var=loaded_artifact
# - debug: msg='{{ component.value._metadata.template | default(loaded_artifact._metadata.template) }}'

- name: 'Create the {{ build_type }} directory: {{ spec.terraplate[build_type].target_dir }}'
  file:
    path: '{{ spec.terraplate[build_type].target_dir }}'
    state: directory

- name: 'Template the template file to {{ spec.terraplate[build_type].target_dir }}/{{ template_base }}'
  template:
    src: '{{ template_base }}.j2'
    dest: '{{ spec.terraplate[build_type].target_dir }}/{{ template_base }}'
