#!/usr/bin/env ansible-playbook
---
- name: Template an AWS Network Security Groups
  hosts: app-backend-security
  tasks:
    - include_vars:
        file: ../application-vars.yml
        name: application
    - include_role:
        name: terraplate/component
      vars:
        manifest:
          # terraplate: '{{ application | combine({name: backend/security})}}'
          # terragrunt: same as now
          # terraform: '{{ env_spec }}'
          # NOTE: providers and remote_states are part of the hash so it's all in one
          application: '{{ application }}'
          component:
            terraplate:
              name: backend/security
            terragrunt:
              dependencies: [../network]
            terraform:
              providers: [aws]
              remote_states: [network]
          providers: '{{ env_spec }}'
            #
            # - metadata:
            #     type: aws
            #   resources: '{{ env_spec }}'
