---
- include_role:
    name: terraplate/spec/component
  vars:
    component: '{{ component_0 }}'

- set_fact:
    spec: "{{ spec | combine({'references': {component_0.key: loaded_artifact}}, recursive=True) }}"

- set_fact:
    spec: "{{ spec | combine({'user': {component_0.key: user_artifact}}, recursive=True) }}"
  when: build_type == 'config'

- include_tasks: component_1.yml
  with_dict: '{{ component_0.value.components }}'
  loop_control:
    loop_var: component_1
  when: component_0.value.components is defined
