---
- include_tasks: module-prompt.yml

- name: Include requested module vars
  include_vars:
    file: '{{ module_vars.source_file }}'
    name: module_spec

- set_fact:
    spec: "{{ {'terraplate': {'dirs': m1, 'module': module_vars, 'plan': {}}} | combine({'components': module_spec}) }}"
