# Component Tasks for aws/tasks/security
---
- name: Include terraplate/debug tasks
  include_role:
    name: terraplate
    tasks_from: debug
  vars:
    called_from: 'aws/tasks/security.yml'
  when: false

- name: Include Component Resource Tasks for aws/vpc/security-group
  include_role:
    name: aws/vpc/security-group
  vars:
    user_key: '{{ item.name }}'
    user_resource: '{{ item }}'
  with_items: '{{ spec.resources.aws_security_groups }}'

- name: Template the CIDR rules
  include_role:
    name: aws/vpc/security-group-rule-cidr
  vars:
    user_key: '{{ item.0.name }}-{{ item.1.name }}'
    user_resource: "{{ item.1 | combine({'security_group_id': '${aws_security_group.' + item.0.name + '.id}'}) }}"
  with_subelements:
    - '{{ spec.resources.aws_security_groups }}'
    - rules
