# Combine manifest values in one place rather than scattered throughout the downstream templates
# This also serves to segment the user manifest from the spec used internally by components and resources
# template_type: "{{ 'ansible' if inventory_hostname == 'localhost' else 'terraform' }}"
---
d0:
  playbook_dir: '{{ playbook_dir }}/playbooks'
  inventory_dir: '{{ inventory_dir }}'
  application:
    name: "{{ application_name | replace('_', '-') | replace('/', '-') }}"
    user_name: '{{ application_name }}'
  namespace:
    name: "{{ namespace | replace('_', '-') | replace('/', '-') }}"
    user_name: '{{ namespace }}'
  component:
    name: "{{ component_name | replace('_', '-') | replace('/', '-') }}"
    user_name: '{{ component_name }}'

d1:
  application:
    inventory:
      dir: '{{ d0.inventory_dir }}/group_vars/{{ d0.application.name }}'
      file: '{{ d0.inventory_dir }}/inventory'
      name: '{{ d0.application.name }}'
    playbook:
      dir: '{{ d0.playbook_dir }}/{{ d0.application.user_name }}'
  namespace:
    inventory:
      name: '{{ d0.application.name }}-{{ d0.namespace.name }}'
    playbook:
      dir: '{{ d0.playbook_dir }}/{{ d0.application.user_name }}/{{ d0.namespace.user_name }}'
  component:
    inventory:
      name: '{{ d0.application.name }}-{{ d0.namespace.name }}-{{ d0.component.name }}'
    playbook:
      dir: '{{ d0.playbook_dir }}/{{ d0.application.user_name }}/{{ d0.namespace.user_name }}/{{ d0.component.user_name }}'

d2:
  application:
    playbook:
      file: '{{ d1.application.playbook.dir }}/all.yml'
      manifest_file: '{{ d1.application.playbook.dir }}/application_manifest.yml'
      variables_file: '{{ d1.application.playbook.dir }}/variables.yml'
  namespace:
    playbook:
      file: '{{ d1.namespace.playbook.dir }}/all.yml'
  component:
    inventory:
      dir: '{{ d0.inventory_dir }}/host_vars/{{ d1.component.inventory.name }}'
    playbook:
      file: '{{ d1.component.playbook.dir }}/component.yml'
      arguments_file: '{{ d1.component.playbook.dir }}/arguments.yml'
      variables_file: '{{ d1.component.playbook.dir }}/variables.yml'
    template:
      name: '{{ template_name }}'
      file: "{{ role_path.split('/')[0:-3] | join('/') }}/providers/{{ template_name.split('_')[0] }}/components/{{ template_name.split('_')[1:] | join('_') }}.yml"

spec: '{{ d0 | combine(d1, recursive=True) | combine(d2, recursive=True) }}'
