---
# project_dir: 'projects/{{ project_name }}'
# tfvars_pattern: '.variables.tfvars'

defaults:
  terraform:
    version: 0.11.7
    binary_home: /usr/local/bin
    binary_url_base: 'https://releases.hashicorp.com/terraform'
  terragrunt:
    version: 0.16.3
    binary_home: /usr/local/bin
    binary_url_base: 'https://github.com/gruntwork-io/terragrunt/releases/download'

base_spec: '{{ defaults | combine(manifest | default({}), recursive=True) }}'

derived_spec:
  terraform:
    file: 'terraform_{{ base_spec.terraform.version }}_linux_amd64'
    binary_path: '{{ base_spec.terraform.binary_home }}/terraform'
  terragrunt:
    binary_path: '{{ base_spec.terragrunt.binary_home }}/terragrunt'

spec: '{{ base_spec | combine(derived_spec, recursive=True) | combine(role_spec, recursive=True) }}'
