---
- debug: var=render_components

- name: Create the target plan directory tree
  file:
    name: '{{ spec.terraplate.plan.target_dir }}'
    state: directory

- name: Template the tfvars file
  template:
    src: main.j2
    dest: '{{ spec.terraplate.plan.target_dir }}/terraform.tfvars'
  vars:
    render_type: tfvars
  when: false

- name: 'Template the plan to {{ spec.terraplate.plan.target_dir }}/main.tf'
  template:
    src: main.j2
    dest: '{{ spec.terraplate.plan.target_dir }}/main.tf'
  vars:
    render_type: arguments
