---
- name: 'Create the target plan directory tree: {{ spec.terraplate.plan.target_dir }}'
  file:
    name: '{{ spec.terraplate.plan.target_dir }}'
    state: directory

- name: 'Template the main.auto.tfvars file to {{ spec.terraplate.plan.target_dir }}/main.auto.tfvars'
  template:
    src: main.j2
    dest: '{{ spec.terraplate.plan.target_dir }}/main.auto.tfvars'
  vars:
    render_type: variables

- name: 'Template the plan to {{ spec.terraplate.plan.target_dir }}/main.tf'
  template:
    src: main.j2
    dest: '{{ spec.terraplate.plan.target_dir }}/main.tf'
  vars:
    render_type: arguments

- name: 'Template the terraform.tfvars file to {{ spec.terraplate.plan.target_dir }}/terraform.tfvars'
  template:
    src: plan-terraform.tfvars.j2
    dest: '{{ spec.terraplate.plan.target_dir }}/terraform.tfvars'
