---
# - name: Fail unless the component name is properly formatted
#   fail:
#     msg: "'component' must be in format application_name/component_name"
#   when: spec.application.name | length == 0

- name: Prompt for the build_type if it has not been supplied
  prompt:
    msg:
      say: Build Type (module, config or plan)
      ask: build_type
      default: plan
  when: build_type is not defined

- include_role:
    name: terraplate/spec

- set_fact:
    render_components: '{{ spec.references | combine(spec.components, recursive=True) | combine(spec.user | default({}), recursive=True) }}'

# - set_fact:
#     spec: "{{ spec | combine({'render': render}, recursive=True) }}"

# - set_fact:
#     spec: "{{ spec | combine({'render': (spec.references | combine(spec.components, recursive=True))}, recursive=True) }}"

- debug:
    var: spec
  when: debug_vars is defined

- name: 'Generate the {{ build_type }}'
  include_tasks: '{{ module_action }}-{{ build_type }}.yml'
