---
- name: Create the source plan directory tree
  file:
    name: '{{ spec.terraplate.plan.source_dir }}'
    state: directory

- debug: var=render_components

- name: Template the component playbook
  template:
    src: main.j2
    dest: '{{ spec.terraplate.plan.source_dir }}/manifest.yml'
  vars:
    render_type: manifest

- name: Template the component variables to a vars file
  template:
    src: main.j2
    dest: '{{ spec.terraplate.plan.source_dir }}/variables.yml'
  vars:
    render_type: variables

- name: Encrypt the component variables vars file with the project's vault password
  command: 'ansible-vault encrypt {{ spec.terraplate.plan.source_dir }}/variables.yml'
  when: encrypt_plan_vars is defined and encrypt_plan_vars
