---
- prompt:
    msg:
      say: Action (new, generate or destroy)
      ask: module_action
      default: '{{ module_action }}'
  when: module_action is defined

- prompt:
    msg:
      say: Action (new, generate or destroy)
      ask: module_action
  when: module_action is not defined

- name: "Run the '{{ module_action }}' tasks"
  include_tasks: '{{ module_action }}.yml'
