---
- name: Is current directory a terraplate project
  lineinfile: 
    dest: ansible.cfg
    line: '# terraplate-project'
  check_mode: yes
  register: presence

- set_fact:
    is_terraplate_project: '{{ not presence.changed }}'

- name: Stop if the current directory is alredy an existing project
  fail:
    msg: 'Cannot create a new project in an already existing project'
  when: is_terraplate_project

- prompt:
    msg:
      say: 'Project name'
      ask: project_name
      default: captain

- prompt:
    msg:
      say: 'Remote State Bucket Name'
      ask: remote_state_bucket_name
      default: com-openmarketinggroup-terraform-state

- prompt:
    msg:
      say: 'Remote State Bucket Region'
      ask: remote_state_bucket_region
      default: ap-southeast-1

- include_role:
    name: terraplate/project
  vars:
    manifest:
      terraform:
        version: 1.0
      terragrunt:
        version: 1.0
