---
- name: Check the current directory for terraplate project artifacts
  lineinfile: 
    dest: ansible.cfg
    line: '# terraplate-project'
  check_mode: yes
  register: presence

- name: Stop if the current directory contains an existing terraplate project
  fail:
    msg: 'Cannot create a new terraplate project inside an existing project'
  when: not presence.changed

- name: Name of the new project
  prompt:
    msg:
      say: Project name
      ask: project_name
      default: '{{ project_name }}'
  when: project_name is defined

- name: Name of the new project
  prompt:
    msg:
      say: Project name
      ask: project_name
  when: project_name is not defined

- include_role:
    name: terraplate/project

# TODO: Implement the check inside the setup task
- name: Install dependencies
  include_role:
    name: terraplate/project
    tasks_from: setup
  when: false
