---
component_manifest:
   resources:
          - metadata:
              # application: '{{ application }}'
              name: 'admin/vcs2'
              # NOTE: Any 'global' defaults can be put here using the resouce type as the key
              # They will be automatically merged
              # TODO: Follow  the same style at the global level and all will be auto merged based on 
              # resource type
              terraform_remote_state:
                defaults:
                  arguments:
                    config:
                      bucket: com-openmarketinggroup-terraform-state
                      region: ap-southeast-1
              # dependecies: []
              # Additional values that are now in the the component stuff
            providers:
              - metadata:
                  type: github
                variables:
                  token: '{{ terraplate_credentials.github_token }}'
                arguments:
                  organization: rails-on-kubernetes
                  alias: us-west
            data_sources:
              - metadata:
                  type: terraform_remote_state
                  name: dns
                arguments:
                  config:
                    key: app/development/backend/network/terraform.tfstate
                    # key: 
            resources:
              - metadata:
                  type: github_repository
                  name: terraplate_devops
                arguments:
                  name: terraplate-devops
                  description: Terraplate Devops Repository
                  private: 'false'
