# admin application vars
---
terraplate:
  root_dir: '{{ globals.terraplate.root_dir }}'
  external_vars_dir: '{{ globals.terraplate.external_vars_dir }}'
  credentials_dir: '{{ globals.terraplate.credentials_dir }}'
  app_name: admin

terragrunt: '{{ globals.terragrunt }}'

terraform: '{{ globals.terraform }}'
