#!/usr/bin/env ansible-playbook
---
- name: Template an AWS Route53 zone with records
  hosts: admin-dns
  tasks:
    - include_vars:
        file: ../application-vars.yml
        name: application
    - include_vars:
        file: zone-vars.yml
        name: manifest
    - include_role:
        name: terraplate/component
