---
kind: aws/route53/domain-with-hosts
application: '{{ application }}'
component:
  terraplate:
    name: dns/domain
  terragrunt:
    dependencies: [../../vcs]
  terraform:
    providers: [aws]
resources:
  zones: '{{ config.resources.admin.dns.zones }}'
