---
application: '{{ application }}'
component:
  terraplate:
    name: dns/domain
  terragrunt:
    dependencies: [../../vcs]
  terraform:
    providers: [aws]
providers: '{{ config.playbooks.admin.dns }}'
