---
terraplate:
  debug_macros: []
  dependencies: []

providers:
  - metadata:
      type: github
      name: main

data_sources:
  - metadata:
      type: template_file
      name: github_repository 
      profile: bucket_env # test

resources:
  - metadata:
      type: github_repository
      name: repo
