---
- name: Load artifact vars
  include_vars:
    file: artifact.yml
    name: main_artifact

- set_fact:
    loaded_artifact: '{{ main_artifact }}'
  when: user_artifact.metadata.profile is not defined

- name: Load profile_artifact vars
  include_vars:
    file: '{{ user_artifact.metadata.profile }}.yml'
    name: profile_artifact
  when: user_artifact.metadata.profile is defined

- set_fact:
    loaded_artifact: '{{ main_artifact | combine(profile_artifact, recursive=True) }}'
  when: user_artifact.metadata.profile is defined
