---
- name: Load base vars
  include_vars:
    file: base.yml
    name: base_vars

- name: Load records vars
  include_vars:
    file: records.yml
    name: profile_vars
  when: component.value.records is defined

- name: Load alias vars
  include_vars:
    file: alias.yml
    name: profile_vars
  when: component.value.alias is defined

- name: Load subdomain vars
  include_vars:
    file: subdomain.yml
    name: profile_vars
  when: component.value.subdomain is defined

- set_fact:
    loaded_artifact: '{{ base_vars | combine(profile_vars | default({}), recursive=True) }}'
