---
metadata:
  type: aws_nat_gateway
  description: A list of route objects. Their keys are documented below.

parents: {}

associations:
  belongs_to:
    aws_vpc:
      arguments:
        vpc_id: id

defaults: {}

definition:
  arguments:
    allocation_id:
      description: The id of the eip to be assigned to this GW
      required: yes
    subnet_id:
      description: The id of the public subnet in which to place the GW
      required: yes
    tags:
      description: A mapping of tags to assign to the resource.
      required: no
  
  attributes:
    id:
      description: The id of the NAT Gateway.
    allocation_id:
      description: The Allocation ID of the Elastic IP address for the gateway.
    subnet_id:
      description: The Subnet ID of the subnet in which the NAT gateway is placed.
    network_interface_id:
      description: The ENI ID of the network interface created by the NAT gateway.
    private_ip:
      description: The private IP address of the NAT Gateway.
    public_ip:
      description: The public IP address of the NAT Gateway.
