---
metadata:
  name: aws_alb_target_group_attachment

parents:
  aws_alb_target_group:
    arguments:
      target_group_arn: arn
  aws_instance:
    arguments:
      target_id: id

defaults:
  arguments:
    port: 80

definition:
  arguments:
    port:
      description: description
    target_group_arn:
      description: The ARN of the target group with which to register targets
    target_id:
      description: The id of the EC2 instance
