---
# NOTE: The certificate_chain must NOT have lines between the certificates
metadata:
  type: aws_iam_server_certificate
  description: Create an IAM Server Certificate

arguments:
  certificate_body:
    description: "The contents of the public key certificate in PEM-encoded format"
    required: yes
  certificate_chain:
    description: "The contents of the certificate chain. This is typically a concatenation of the PEM-encoded public key certificates of the chain."
    required: no
  name:
    description: "The name of the Server Certificate. Do not include the path in this value. If omitted, Terraform will assign a random, unique name."
    required: no
  private_key:
    description: "The contents of the private key in PEM-encoded format"
    required: yes

# Needs to be set using:
#   export TF_VAR_iam_server_certificate_path=
env_vars:
  path:
    description: The path on local FS to the certificate

attributes:
  arn:
    description: The Amazon Resource Name (ARN) specifying the server certificate
  id:
    description: The unique Server Certificate name
  name:
    description: The unique Server Certificate name
