---
resource_meta:
  path: aws
  ns: ec2
  name: alb

variables:
  # access_logs:
  #   type: map
  #   description: description
  #   default:
  #     bucket: foo
  #     prefix: bar
  enable_deletion_protection:
    description: description
    default: 'false'
  name:
    description: description
    default: alb
  internal:
    description: description
    default: 'false'
  tags:
    type: map
    description: Hash of name-value pairs to tag the instance
    default:
      Name: Change Me!

external_vars:
  security_groups:
    description: List of Security Group IDs to attach to the ALB
    type: list
  subnets:
    description: List of subnet IDs to attach to the ALB
    type: list

output_vars:
  arn_suffix:
    description: The ARN suffix for use with CloudWatch Metrics
    value: aws_alb.resource.arn_suffix
  dns_name:
    description: The DNS name of the load balancer
    value: aws_alb.resource.dns_name
  load_balancer_arn:
    description: The ARN of the load balancer (matches id)
    value: aws_alb.resource.arn
  zone_id:
    description: The canonical hosted zone ID of the load balancer (to be used in a Route 53 Alias record)
    value: aws_alb.resource.zone_id
