---
metadata:
  type: aws_iam_access_key
  description: Provides an IAM access key. This is a set of credentials that allow API requests to be made as an IAM user

arguments:
  user:
    description: The IAM user to associate with this access key
    required: yes
  pgp_key:
    description: Either a base-64 encoded PGP public key, or a keybase username in the form keybase:some_person_that_exists
    required: no

attributes:
  id:
    description: The access key id
  secret:
    description: The secret access key. Note that this will be written to the state file. Please supply a pgp_key instead, which will prevent the secret from being stored in plain text
