# Resource Vars for aws/ec2/elb
---
metadata:
  type: aws_elb
  description: 'Provides an Elastic Load Balancer resource, also known as a "Classic Load Balancer"'

arguments:
  # access_logs:
  #   type: map
  #   description: description
  #   default:
  #     bucket: foo
  #     bucket_prefix: bar
  #     interval: 60
  # availability_zones:
  #   type: list
  #   description: description
  #   default: []
  connection_draining:
    description: description
    default: 'true'
  connection_draining_timeout:
    description: description
    default: 4
  cross_zone_load_balancing:
    description: description
    default: 'false'
  health_check:
    type: map
    default:
      target: 'TCP:3000'
      # description: The protocol:port instances respond to keep alive traffic from the ELB
      healthy_threshold: 10
      # description: The number of keep-alives the instance must respond to to be considered healthy
      unhealthy_threshold: 2
      # description: The number of keep-alives the instance must fail to respond to to be considered unhealthy
      timeout: 
      # description: The number of seconds the instance has to respond to keep-alives to be considered healthy
      interval: 30
      # description: The duration in seconds the instance is sent keep-alives
  idle_timeout:
    description: description
    default: 400
  listener:
    type: map
    default:
      instance_port: 3000
      # description: The port instances listen for traffic from the ELB
      instance_protocol: http
      # description: The protocol instances listen for traffic from the ELB
      lb_port: 443
      # description: The port the ELB listens for traffic from the originator
      lb_protocol: https
      # description: The protocol the ELB listens for traffic from the originator
      ssl_certificate_id: ${var.listener_ssl_certificate_id}
      # description: The IAM certificate arn
  name:
    description: description
    default: elb
  tags:
    type: map
    description: Hash of name-value pairs to tag the instance
    default:
      Name: Change Me!
    required: false

      # external_vars:
  listener_ssl_certificate_id:
    description: The IAM certificate arn
  security_groups:
    description: List of Security Group IDs to attach to the ELB
    type: list
  subnets:
    description: List of subnet IDs to attach to the ELB
    type: list

attributes:
  dns_name:
    description: description
  id:
    description: description
  zone_id:
    description: description
