---
metadata:
  type: aws_internet_gateway
  description: Provides a resource to create a VPC Internet Gateway.

parents: {}

defaults: {}

definition:
  arguments:
    tags:
      description: A mapping of tags to assign to the resource.
      required: no
      type: map
    vpc_id:
      description: The VPC ID to create in.
      required: yes
      reference_from:
        aws_vpc: id
  
  attributes:
    id:
      description: The id of the Internet Gateway.
