---
metadata:
  type: aws_elb
  description: 'Provides an Elastic Load Balancer resource, also known as a "Classic Load Balancer"'

parents: {}

defaults:
  arguments:
    health_check:
      target: 'TCP:3000'
      # description: The protocol:port instances respond to keep alive traffic from the ELB
      healthy_threshold: 10
      # description: The number of keep-alives the instance must respond to to be considered healthy
      unhealthy_threshold: 2
      # description: The number of keep-alives the instance must fail to respond to to be considered unhealthy
      timeout: 
      # description: The number of seconds the instance has to respond to keep-alives to be considered healthy
      interval: 30
      # description: The duration in seconds the instance is sent keep-alives
    listener:
      instance_port: 3000
      # description: The port instances listen for traffic from the ELB
      instance_protocol: http
      # description: The protocol instances listen for traffic from the ELB
      lb_port: 443
      # description: The port the ELB listens for traffic from the originator
      lb_protocol: https
      # description: The protocol the ELB listens for traffic from the originator
      ssl_certificate_id: ${var.listener_ssl_certificate_id}
      # description: The IAM certificate arn

definition:
  arguments:
    # access_logs:
    #   type: map
    #   description: description
    #   default:
    #     bucket: foo
    #     bucket_prefix: bar
    #     interval: 60
    # availability_zones:
    #   type: list
    #   description: description
    #   default: []
    connection_draining:
      # default: 'true'
      description: description
      required: no
    connection_draining_timeout:
      # default: 4
      description: description
      required: no
    cross_zone_load_balancing:
      # default: 'false'
      description: description
      required: no
    health_check:
      required: no
      type: map
    idle_timeout:
      # default: 400
      description: description
      required: no
    listener:
      required: no
      type: map
    name:
      # default: elb
      description: description
      required: no
    tags:
      type: map
      description: Hash of name-value pairs to tag the instance
      required: no
    listener_ssl_certificate_id:
      description: The IAM certificate arn
      required: no
    security_groups:
      description: List of Security Group IDs to attach to the ELB
      required: no
      type: list
    subnets:
      description: List of subnet IDs to attach to the ELB
      required: no
      type: list
  
  attributes:
    dns_name:
      description: description
    id:
      description: description
    zone_id:
      description: description
