---
- debug:
    var: provider
  when: false

- name: Include render tasks for Data Sources artifacts
  include_tasks: artifact.yml
  vars:
    provider_path: data_sources
    provider_doc_path: d
    render_type: data
    attribute_prefix: data.
  with_items: '{{ provider.data_sources }}'
  loop_control:
    loop_var: spec_artifact
  when: provider.data_sources is defined

- name: Include render tasks for Resources artifacts
  include_tasks: artifact.yml
  vars:
    provider_path: resources
    provider_doc_path: r
    render_type: resource
  with_items: '{{ provider.resources }}'
  loop_control:
    loop_var: spec_artifact
  when: provider.resources is defined
