---
- name: '^^^^^ BEGIN {{ reference_artifact_path }} ^^^^^'
  debug:
    var: '{{ debug_item }}'
  with_items: [provider_type, artifact_path, artifact_type, artifact_name, user_artifact_name, reference_artifact_vars_file_path, qa_path, component_artifact, user_component]
  loop_control:
    loop_var: debug_item

#- set_fact:
#    user_artifact: "{{ user_component[qa_path][artifact_type + '_' + artifact_name] }}"


# - debug:
#     msg: "{{ user_component[qa_path][artifact_type + '_' + artifact_name] }}"
#   when: false

- name: '{{ reference_artifact_path }} - Check if artifact vars_file exists'
  stat:
    path: '{{ reference_artifact_vars_file_path }}'
  register: vars_file

- name: Set template_content to null before loading artifact
  set_fact:
    template_content: null
    loaded_artifact: null

- name: Include reference_artifact vars file from file
  include_vars:
    file: '{{ reference_artifact_vars_file_path }}'
    name: vars_loaded_artifact
  when: vars_file.stat.exists

- set_fact:
    loaded_artifact: '{{ vars_loaded_artifact }}'
  when: vars_file.stat.exists

- name: Include role reference_artifact_path
  include_role:
    name: '{{ reference_artifact_path }}'
  vars:
    profile: "{{ component_artifact.metadata.profile | default('') }}"
    # profile: "{{ user_artifact.metadata.profile | default(reference_artifact.metadata.profile) | default('') }}"
  when: not vars_file.stat.exists

- set_fact:
    reference_artifact: '{{ loaded_artifact }}'

- name: 'Debug {{ reference_artifact_path }}'
  debug:
    var: '{{ debug_item }}'
  with_items: [reference_artifact, user_artifact]
  loop_control:
    loop_var: debug_item

- set_fact:
    variables:
      user: '{{ user_artifact.variables | default({}) }}'
      component: '{{ component_artifact.variables | default({}) }}'
      reference: '{{ reference_artifact.defaults.variables | default({}) }}'
    arguments:
      user: '{{ user_artifact.arguments | default({}) }}'
      component: '{{ component_artifact.arguments | default({}) }}'
      reference: '{{ reference_artifact.defaults.arguments | default({}) }}'

- name: 'Debug {{ reference_artifact_path }}'
  debug:
    var: '{{ debug_item }}'
  with_items: [variables, arguments]
  loop_control:
    loop_var: debug_item

- name: Set values on artifact variables
  include_tasks: prompt.yml
  vars:
    question_type: variables
    default: "{{ variables.user[question.key] | default(variables.component[question.key]) | default(variables.reference[question.key]) | default('') }}"
  with_dict: '{{ reference_artifact.definition.variables }}'
  loop_control:
    loop_var: question
  when: reference_artifact.definition.variables is defined # and component_artifact[question_type][question.key] is not defined

- name: Set values on artifact arguments
  include_tasks: prompt.yml
  vars:
    question_type: arguments
    default: "{{ arguments.user[question.key] | default(arguments.component[question.key]) | default(arguments.reference[question.key]) | default('')}}"
  with_dict: '{{ reference_artifact.definition.arguments }}'
  loop_control:
    loop_var: question
  when: reference_artifact.definition.arguments is defined and reference_artifact.definition.arguments[question.key].prompt is not defined and reference_artifact.definition.arguments[question.key].type is not defined # and component_artifact[question_type][question.key] is not defined

- name: '^^^^^ END {{ reference_artifact_path }} ^^^^^'
  debug:
    var: qa
