---
# The default value is based on priority:
# 1: The user_artifact value if provided
# 2: The component_artifact value if defined
# 3: The reference_artifact default value if defined
# 4: A blank string

# - debug: msg='{{ reference_artifact.definition.arguments[question.key] }}'
- name: 'Debug {{ question.key }}'
  debug:
    var: question

- name: "Provide the value for the {{ artifact_type }} {{ question_type | replace('s', '') }} '{{ question.key }}'"
  prompt:
    msg:
      say: "{{ question.value.description }}\n{{ question.key }}"
      ask: answer
      default: '{{ default }}'

- set_fact:
    qa: '{{ qa | combine({qa_path: {artifact_full_name: {question_type: {question.key: answer}}}}, recursive=True) }}'
