---
provider_type: "{{ component_artifact.metadata.type.split('_')[0] }}"

reference_artifact_path: 'providers/{{ provider_type }}{{ artifact_path }}/{{ artifact_type }}'

# Example: aws/resource/route53_record
reference_artifact_vars_file_path: "{{ role_path.split('/')[0:-3] | join('/') }}/{{ reference_artifact_path }}.yml"

artifact_name: "{{ component_artifact.metadata.name }}"
artifact_full_name: '{{ component_artifact.metadata.type }}_{{ artifact_name }}'

user_artifact_name: "{{ component_artifact.metadata.type }}_{{ component_artifact.metadata.name }}"
user_artifact: "{{ user_component[qa_path][user_artifact_name] | default({}) }}"
