---
- name: 'Render the artifact tfvars for {{ template_data.artifact.full_name }}'
  blockinfile:
    create: yes
    dest: '{{ spec.terraplate.component.variables.full_file_name }}'
    marker: '# {mark} {{ template_data.artifact.full_name }}'
    block: "{{ lookup('template', 'tfvars.j2') }}"
  when: user_artifact.variables | length > 0

- name: 'Render the artifact template for {{ template_data.artifact.full_name }}'
  blockinfile:
    create: yes
    dest: '{{ spec.terraplate.component.dir }}/{{ spec.terraplate.component.file_name }}'
    marker: '# {mark} {{ template_data.artifact.full_name }}'
    block: "{{ lookup('template', 'main.tf.j2') }}"
