---
- name: Load artifact vars
  include_vars:
    file: base.yml
    name: base_vars

- name: Load profile's artifact vars
  include_vars:
    file: '{{ component.value._metadata.profile }}.yml'
    name: profile_vars
  when: component.value._metadata is defined and component.value._metadata.profile is defined

- set_fact:
    loaded_artifact: '{{ base_vars | combine(profile_vars | default({}), recursive=True) }}'
