---
- name: Load artifact vars
  include_vars:
    file: artifact.yml
    name: base_artifact

#
# - set_fact:
#     loaded_artifact: '{{ base_artifact }}'
#   when: profile is not defined

- name: Load profile's artifact vars
  include_vars:
    file: '{{ profile }}.yml'
    name: profile_artifact
  when: profile is defined

- set_fact:
    loaded_artifact: '{{ base_artifact | combine(profile_artifact | default({}), recursive=True) }}'
    # when: profile is defined
