#!/usr/bin/env ansible-playbook
---
- name: Template EC2 ssh key pairs
  hosts: admin-security
  tasks:
    - include_role:
        name: terraplate/utils
        tasks_from: ssh-key-gen
      vars:
        private_key_path: '{{ terraform_vars.key_path }}/{{ item.arguments.key_name }}'
      with_items: '{{ config.playbooks.admin.compute.key_pairs[0].resources }}'

    - include_vars:
        file: ../application-vars.yml
        name: application

    - include_role:
        name: terraplate/component
      vars:
        manifest:
          application: '{{ application }}'
          component:
            terraplate:
              name: security/compute
            terragrunt:
              dependencies: []
              external_vars:
                key_path: '{{ terraform_vars.key_path }}'
            terraform:
              providers: [aws]
          providers: '{{ config.playbooks.admin.compute.key_pairs }}'
