# Resource Vars for aws/ec2/instance
---
resource:
  meta:
    type: aws_instance
    description: Create an EC2 Instance in a VPC subnet and AZ

  related_resources:
    aws_eip:
      var_name: instance
    aws_elb_attachment:
      var_name: instance

  input_vars:
    # region:
    #  description: description
    amis:
      type: map
      description: Hash of amis per region
      required: false
  
  variables:
    ami:
      description: description
      default: "${lookup(var.amis, var.region)}"
      required: true
    associate_public_ip_address:
      description: description
      default: 'true'
    availability_zone:
      description: description
    ebs_optimized:
      description: description
      default: 'false'
    instance_type:
      description: description
      default: t2.micro
      required: true
    key_name:
      description: The name of the ssh key pair
    monitoring:
      description: description
      default: 'false'
    # private_ip:
    #   description: description
    #   default: 172.16.1.184
    root_block_device:
      description: description
      required: false
      type: map
      # default:
      # volume_type: gp2
      # volume_size: 8
      # delete_on_termination: yes # 'true'
    source_dest_check:
      description: description
      default: 'true'
    tags:
      type: map
      description: Hash of name-value pairs to tag the instance
      default: { 'Name': 'Change Me!' }
  
  # external_vars:
    vpc_security_group_ids:
      type: list
      description: The security group id for the instance
    subnet_id:
      description: description
  
  output_vars:
    id:
      description: The ec2 instance id
    private_ips:
      type: list
      description: description
      name: '*.private_ip'
    public_ip:
      description: The public IP address assigned to the instance, if applicable.
