---
metadata:
  type: aws_acm_certificate
  description: "Use this data source to get the ARN of a certificate in AWS Certificate Manager (ACM). The process of requesting and verifying a certificate in ACM requires some manual steps, which means that Terraform cannot automate the creation of ACM certificates. But using this data source, you can reference them by domain without having to hard code the ARNs as input."
  attribute_prefix: data.

parents: {}

defaults:
  arguments:
    statuses: ['ISSUED']

definition:
  arguments:
    domain:
      description: "The domain of the certificate to look up. If no certificate is found with this name, an error will be returned"
      required: yes
    statuses:
      description: "A list of statuses on which to filter the returned list. Valid values are PENDING_VALIDATION, ISSUED, INACTIVE, EXPIRED, VALIDATION_TIMED_OUT, REVOKED and FAILED. If no value is specified, only certificates in the ISSUED state are returned"
      required: no
      type: list
    types:
      description: A list of types on which to filter the returned list. Valid values are AMAZON_ISSUED and IMPORTED.
      required: no
    most_recent:
      description: "If set to true, it sorts the certificates matched by previous criteria by the NotBefore field, returning only the most recent one. If set to false, it returns an error if more than one certificate is found. Defaults to false."
      required: no
  
  attributes:
    arn:
      description: "Set to the ARN of the found certificate, suitable for referencing in other resources that support ACM certificates"
