---
global_vars:
  amis:
    debian_stretch: # AMI IDs from https://wiki.debian.org/Cloud/AmazonEC2Image/Stretch
      ap-northeast-1: ami-93552ff5
      ap-northeast-2: ami-c4d578aa
      ap-south-1: ami-79673b16
      ap-southeast-1: ami-c3c789bf
      ap-southeast-2: ami-e9ce098b
      ca-central-1: ami-3fd3545b
      eu-central-1: ami-b82240d7
      eu-west-1: ami-fe4b3287
      eu-west-2: ami-2ef21649
      eu-west-3: ami-af77c1d2
      sa-east-1: ami-74387018
      us-east-1: ami-0dc82b70
      us-east-2: ami-295c6b4c
      us-west-1: ami-8c828aec
      us-west-2: ami-d967e8a1
