---
# Becuase fact collection is turned off:
ansible_env:
  HOME: /home/vagrant
globals:
  terraplate:
    root_dir: '{{ inventory_dir.split("/")[0:-2] | join("/") }}/terraform'
    external_vars_dir: '{{ inventory_dir.split("/")[0:-2] | join("/") }}/terraform-vars'
    credentials_dir: '{{ inventory_dir.split("/")[0:-2] | join("/") }}/secrets/credentials.tfvars'
  
  terragrunt:
    credentials_path: ../secrets/credentials.tfvars
    external_vars_path: ../terraform-vars
    remote_state:
      region: ap-southeast-1
      # Example of segmenting terraform remote state buckets by environment if preferred:
      # bucket: '{{ config.globals.remote_state_name }}-{{ terraplate.env.tld }}'
      bucket: '{{ config.globals.remote_state_name }}'
      dynamodb_table: '{{ config.globals.remote_state_name }}'
  
  terraform:
    providers:
      aws:
        region: ap-southeast-1
      github:
        # Token is provided from encrypted inventory/all/secrets.yml
        token: var.github_token
        organization: '{{ config.globals.github_organization }}'
    remote_states:
      dns:
        key: admin/dns/domain
        # If the remote state is in a different bucket:
        # bucket: some-other-bucket-name-containing-terrform-state
      #
      # network:
      #   key: 'app/{{ env.terraplate.tld }}/backend/network'
      # security:
      #   key: 'app/{{ env.terraplate.tld }}/backend/security'
