---
settings:
  bucket_prefix: com-example
  github_organization: example
  zone_domain: example.com
  host_1:
    name: www
    address: 8.8.8.8
  host_2:
    name: www2
    address: 8.8.8.8
  ec2_key_name: rails_server_1_admin

globals:
  terraplate:
    root_dir: '{{ inventory_dir.split("/")[0:-2] | join("/") }}/terraform'
    credentials_path: '{{ inventory_dir.split("/")[0:-2] | join("/") }}/secrets/credentials.tfvars'
  
  terragrunt:
    credentials_path: ../secrets/credentials.tfvars
    remote_state:
      region: ap-southeast-1
      bucket: '{{ settings.bucket_prefix }}-terraform-state'
      # Segment terraform remote state buckets by environment if preferred:
      # bucket: '{{ terraform_bucket_prefix }}-terraform-state-{{ terraplate.env.tld }}'
      dynamodb_table: '{{ settings.bucket_prefix }}-terraform-lock-table'
  
  terraform:
    providers:
      aws:
        region: ap-southeast-1
      github:
        token: var.github_token
        organization: '{{ settings.github_organization }}'
    remote_states:
      dns:
        key: admin/app-dns
        bucket: '{{ settings.bucket_prefix }}-hash-terraform-state'
      network:
      security:

global_vars:
  amis:
    debian_stretch: # AMI IDs from https://wiki.debian.org/Cloud/AmazonEC2Image/Stretch
      ap-northeast-1: ami-93552ff5
      ap-northeast-2: ami-c4d578aa
      ap-south-1: ami-79673b16
      ap-southeast-1: ami-c3c789bf
      ap-southeast-2: ami-e9ce098b
      ca-central-1: ami-3fd3545b
      eu-central-1: ami-b82240d7
      eu-west-1: ami-fe4b3287
      eu-west-2: ami-2ef21649
      eu-west-3: ami-af77c1d2
      sa-east-1: ami-74387018
      us-east-1: ami-0dc82b70
      us-east-2: ami-295c6b4c
      us-west-1: ami-8c828aec
      us-west-2: ami-d967e8a1
