---
# The default value is based on priority:
# 1: The user_artifact value if provided
# 2: The component_artifact value if defined
# 3: The reference_artifact default value if defined
# 4: A blank string

# - name: "Debug question '{{ question.key }}'"
#   debug:
#     var: question

- name: "Provide the value for the {{ reference_component.metadata.type }} {{ question_type | replace('s', '') }} '{{ question.key }}'"
  prompt:
    msg:
      say: "\n{{ question.value.description }}\n{{ component.key }} {{ question_type | replace('s', '') }} '{{ question.key }}'"
      ask: answer
      default: '{{ default }}'
  when: default is string

- name: Update user_component with value from prompt
  set_fact:
    user_artifact: '{{ user_artifact | combine({question_type: {question.key: answer}}, recursive=True)}}'
  when: default is string
