#!/usr/bin/env ansible-playbook
---
- name: Render GitHub Repositories
  hosts: admin-vcs
  tasks:
    - include_vars:
        file: ../application-vars.yml
        name: application
    - include_role:
        name: terraplate/component
      vars:
        manifest:
          kind: github/vcs
          application: '{{ application }}'
          component:
            terraplate:
              name: vcs
            terragrunt:
              dependencies: []
            terraform:
              providers: [github]
          providers: '{{ config.playbooks.admin.vcs.repos }}'
